/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    products: Product;
    blogs: Blog;
    partners: Partner;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    blogs: BlogsSelect<false> | BlogsSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  first_name: string;
  last_name: string;
  roles?: ('admin' | 'editor' | 'viewer')[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  folder?: (string | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: string;
  name: string;
  folder?: (string | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: string | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: string | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  name: string;
  main_description: string;
  additional_description?: string | null;
  product_image: string | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs".
 */
export interface Blog {
  id: string;
  author: string | User;
  title: string;
  overview: string;
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  tags: string;
  blog_image: string | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: string;
  name: string;
  partner_image?: (string | null) | Media;
  location: (
    | 'jakarta_pusat'
    | 'jakarta_barat'
    | 'jakarta_timur'
    | 'jakarta_utara'
    | 'jakarta_selatan'
    | 'kepulauan_seribu'
    | 'bandung_wetan'
    | 'bandung_coblong'
    | 'bandung_cidadap'
    | 'bandung_sukajadi'
    | 'bandung_sukasari'
    | 'bandung_andir'
    | 'bandung_kiaracondong'
    | 'bandung_rancasari'
    | 'bekasi_barat'
    | 'bekasi_timur'
    | 'bekasi_utara'
    | 'bekasi_selatan'
    | 'bekasi_medansatria'
    | 'bekasi_pondokgede'
    | 'depok_beji'
    | 'depok_cimanggis'
    | 'depok_pancoran_mas'
    | 'depok_sukmajaya'
    | 'depok_sawangan'
    | 'depok_limo'
    | 'bogor_utara'
    | 'bogor_selatan'
    | 'bogor_barat'
    | 'bogor_timur'
    | 'bogor_tengah'
    | 'bogor_tanah_sareal'
    | 'cimahi_utara'
    | 'cimahi_tengah'
    | 'cimahi_selatan'
    | 'cirebon_harjamukti'
    | 'cirebon_kejaksan'
    | 'cirebon_kesambi'
    | 'cirebon_lemahwungkuk'
    | 'sukabumi_cikole'
    | 'sukabumi_citamiang'
    | 'sukabumi_lembursitu'
    | 'tangsel_serpong'
    | 'tangsel_serpong_utara'
    | 'tangsel_pamulang'
    | 'tangsel_ciputat'
    | 'tangsel_ciputat_timur'
    | 'tangsel_pondok_aren'
    | 'tangerang_ciledug'
    | 'tangerang_karawaci'
    | 'tangerang_neglasari'
    | 'tangerang_periuk'
    | 'cilegon_cibeber'
    | 'cilegon_ciwandan'
    | 'cilegon_jombang'
    | 'serang_cipocok_jaya'
    | 'serang_curug'
    | 'serang_kasemen'
    | 'semarang_barat'
    | 'semarang_timur'
    | 'semarang_utara'
    | 'semarang_selatan'
    | 'semarang_tembalang'
    | 'semarang_candisari'
    | 'solo_banjarsari'
    | 'solo_jebres'
    | 'solo_laweyan'
    | 'solo_pasar_kliwon'
    | 'solo_serengan'
    | 'magelang_utara'
    | 'magelang_tengah'
    | 'magelang_selatan'
    | 'tegal_barat'
    | 'tegal_timur'
    | 'tegal_selatan'
    | 'pekalongan_barat'
    | 'pekalongan_timur'
    | 'pekalongan_selatan'
    | 'pekalongan_utara'
    | 'yogyakarta_kraton'
    | 'yogyakarta_gondokusuman'
    | 'yogyakarta_jetis'
    | 'yogyakarta_umbulharjo'
    | 'yogyakarta_kotagede'
    | 'surabaya_pusat'
    | 'surabaya_barat'
    | 'surabaya_timur'
    | 'surabaya_utara'
    | 'surabaya_selatan'
    | 'malang_klojen'
    | 'malang_blimbing'
    | 'malang_lowokwaru'
    | 'malang_sukun'
    | 'malang_kedungkandang'
    | 'batu_batu'
    | 'batu_bumiaji'
    | 'batu_junrejo'
    | 'sidoarjo_waru'
    | 'sidoarjo_taman'
    | 'sidoarjo_candi'
    | 'sidoarjo_buduran'
    | 'kediri_mojoroto'
    | 'kediri_kota'
    | 'kediri_pesantren'
    | 'madiun_kartoharjo'
    | 'madiun_manguharjo'
    | 'madiun_taman'
    | 'probolinggo_kanigaran'
    | 'probolinggo_wonoasih'
    | 'probolinggo_mayangan'
    | 'pasuruan_gadingrejo'
    | 'pasuruan_purworejo'
    | 'pasuruan_bugulkidul'
    | 'mojokerto_magersari'
    | 'mojokerto_prajurit_kulon'
    | 'gresik_kota'
    | 'gresik_manyar'
    | 'denpasar_utara'
    | 'denpasar_timur'
    | 'denpasar_barat'
    | 'denpasar_selatan'
    | 'badung_kuta'
    | 'badung_kuta_selatan'
    | 'badung_kuta_utara'
    | 'badung_mengwi'
    | 'badung_abiansemal'
    | 'gianyar_ubud'
    | 'gianyar_kota'
    | 'gianyar_sukawati'
    | 'tabanan_kota'
    | 'tabanan_kediri'
    | 'mataram_ampenan'
    | 'mataram_cakranegara'
    | 'mataram_kota'
    | 'mataram_sekarbela'
    | 'lombok_barat_senggigi'
    | 'lombok_barat_gerung'
    | 'kupang_oebobo'
    | 'kupang_maulafa'
    | 'kupang_kelapa_lima'
    | 'kupang_alak'
    | 'kupang_kota_lama'
    | 'medan_timur'
    | 'medan_barat'
    | 'medan_utara'
    | 'medan_selatan'
    | 'medan_kota'
    | 'medan_johor'
    | 'medan_sunggal'
    | 'medan_denai'
    | 'binjai_kota'
    | 'binjai_utara'
    | 'binjai_selatan'
    | 'pematangsiantar_barat'
    | 'pematangsiantar_timur'
    | 'pematangsiantar_utara'
    | 'padang_barat'
    | 'padang_timur'
    | 'padang_utara'
    | 'padang_koto_tangah'
    | 'padang_kuranji'
    | 'bukittinggi_guguak_panjang'
    | 'bukittinggi_aur_birugo_tigo_baleh'
    | 'pekanbaru_marpoyan_damai'
    | 'pekanbaru_tampan'
    | 'pekanbaru_rumbai'
    | 'pekanbaru_payung_sekaki'
    | 'pekanbaru_sukajadi'
    | 'batam_kota'
    | 'batam_lubuk_baja'
    | 'batam_sekupang'
    | 'batam_nongsa'
    | 'tanjungpinang_bukit_bestari'
    | 'tanjungpinang_kota'
    | 'palembang_ilir_timur_i'
    | 'palembang_ilir_timur_ii'
    | 'palembang_ilir_barat_i'
    | 'palembang_ilir_barat_ii'
    | 'palembang_seberang_ulu_i'
    | 'palembang_seberang_ulu_ii'
    | 'palembang_sukarami'
    | 'lubuklinggau_barat_i'
    | 'lubuklinggau_timur_i'
    | 'pangkalpinang_taman_sari'
    | 'pangkalpinang_bukit_intan'
    | 'pangkalpinang_pangkal_balam'
    | 'bandar_lampung_tanjung_karang_pusat'
    | 'bandar_lampung_tanjung_karang_timur'
    | 'bandar_lampung_tanjung_karang_barat'
    | 'bandar_lampung_kedaton'
    | 'metro_pusat'
    | 'metro_timur'
    | 'karawang_kota'
    | 'bekasi_kab_cikarang'
    | 'tangsel_bsd'
    | 'pontianak_kota'
    | 'pontianak_selatan'
    | 'pontianak_utara'
    | 'pontianak_timur'
    | 'pontianak_barat'
    | 'pontianak_tenggara'
    | 'palangka_raya_jekan_raya'
    | 'palangka_raya_pahandut'
    | 'palangka_raya_sabangau'
    | 'banjarmasin_timur'
    | 'banjarmasin_barat'
    | 'banjarmasin_tengah'
    | 'banjarmasin_utara'
    | 'banjarmasin_selatan'
    | 'banjarbaru_utara'
    | 'banjarbaru_selatan'
    | 'balikpapan_kota'
    | 'balikpapan_tengah'
    | 'balikpapan_selatan'
    | 'balikpapan_utara'
    | 'balikpapan_barat'
    | 'samarinda_kota'
    | 'samarinda_ulu'
    | 'samarinda_ilir'
    | 'samarinda_sungai_kunjang'
    | 'ppu_sepaku'
    | 'tarakan_barat'
    | 'tarakan_timur'
    | 'tarakan_utara'
    | 'tarakan_tengah'
    | 'manado_wenang'
    | 'manado_sario'
    | 'manado_malalayang'
    | 'manado_tikala'
    | 'bitung_tengah'
    | 'bitung_maesa'
    | 'gorontalo_kota_barat'
    | 'gorontalo_dumbo_raya'
    | 'gorontalo_hulonthalangi'
    | 'palu_barat'
    | 'palu_timur'
    | 'palu_utara'
    | 'palu_selatan'
    | 'palu_tatanga'
    | 'mamuju_kota'
    | 'mamuju_simboro'
    | 'makassar_ujung_pandang'
    | 'makassar_panakkukang'
    | 'makassar_biringkanaya'
    | 'makassar_tamalate'
    | 'makassar_manggala'
    | 'parepare_ujung'
    | 'parepare_soreang'
    | 'kendari_baruga'
    | 'kendari_kota'
    | 'kendari_mandonga'
    | 'baubau_murhum'
    | 'baubau_kokalukuna'
    | 'ambon_sirimau'
    | 'ambon_nusaniwe'
    | 'ambon_baguala'
    | 'ternate_utara'
    | 'ternate_selatan'
    | 'ternate_tengah'
    | 'manokwari_barat'
    | 'manokwari_timur'
    | 'sorong_barat'
    | 'sorong_timur'
    | 'sorong_utara'
    | 'sorong_manoi'
    | 'sorong_kab_aimas'
    | 'sorong_kab_klabot'
    | 'jayapura_abepura'
    | 'jayapura_heram'
    | 'jayapura_utara'
    | 'jayapura_selatan'
    | 'jayawijaya_wamena'
    | 'jayawijaya_asolokobal'
    | 'nabire_kota'
    | 'mimika_mimika_baru'
    | 'mimika_tembagapura'
    | 'merauke_kota'
    | 'merauke_muting'
    | 'banda_aceh_baiturrahman'
    | 'banda_aceh_meuraxa'
    | 'banda_aceh_kuta_alam'
    | 'lhokseumawe_banda_sakti'
    | 'lhokseumawe_muara_dua'
    | 'bengkulu_gading_cempaka'
    | 'bengkulu_ratu_agung'
    | 'jambi_timur'
    | 'jambi_selatan'
    | 'jambi_kota_baru'
    | 'payakumbuh_barat'
    | 'payakumbuh_timur'
    | 'ppu_penajam'
    | 'ppu_babulu'
    | 'bima_kota'
    | 'dompu_kota'
    | 'badung_uluwatu'
    | 'badung_seminyak'
    | 'badung_canggu'
    | 'badung_nusa_dua'
    | 'badung_jimbaran'
    | 'lombok_tengah_kuta_mandalika'
    | 'lombok_tengah_sengkol'
    | 'semarang_kota_lama'
    | 'yogyakarta_malioboro'
    | 'jakarta_kota_tua'
    | 'jakarta_ancol'
    | 'bandung_antapani'
    | 'bandung_arcamanik'
    | 'bandung_bojongloa_kaler'
    | 'bandung_bojongloa_kidul'
    | 'bandung_gedebage'
    | 'surabaya_tegalsari'
    | 'surabaya_genteng'
    | 'surabaya_wonokromo'
    | 'surabaya_rungkut'
    | 'surabaya_sukolilo'
    | 'medan_tuntungan'
    | 'medan_area'
    | 'medan_polonia'
    | 'makassar_ujung_tanah'
    | 'makassar_rappocini'
    | 'manado_bunaken'
    | 'manado_mapanget'
  )[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'blogs';
        value: string | Blog;
      } | null)
    | ({
        relationTo: 'partners';
        value: string | Partner;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: string | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  first_name?: T;
  last_name?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  main_description?: T;
  additional_description?: T;
  product_image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs_select".
 */
export interface BlogsSelect<T extends boolean = true> {
  author?: T;
  title?: T;
  overview?: T;
  content?: T;
  tags?: T;
  blog_image?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  partner_image?: T;
  location?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}