/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    products: Product;
    blogs: Blog;
    partners: Partner;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    blogs: BlogsSelect<false> | BlogsSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  first_name: string;
  last_name: string;
  roles?: ('admin' | 'editor' | 'viewer')[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  folder?: (string | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: string;
  name: string;
  folder?: (string | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: string | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: string | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  name: string;
  main_description: string;
  additional_description?: string | null;
  product_image: string | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs".
 */
export interface Blog {
  id: string;
  author: string | User;
  title: string;
  overview: string;
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  tags: string;
  blog_image: string | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: string;
  name: string;
  partner_image?: (string | null) | Media;
  location: (
    | 'Jakarta Pusat'
    | 'Jakarta Barat'
    | 'Jakarta Timur'
    | 'Jakarta Utara'
    | 'Jakarta Selatan'
    | 'Kepulauan Seribu'
    | 'Serpong (Tangsel)'
    | 'Serpong Utara (Tangsel)'
    | 'Pamulang (Tangsel)'
    | 'Ciputat (Tangsel)'
    | 'Ciputat Timur (Tangsel)'
    | 'Pondok Aren (Tangsel)'
    | 'Ciledug (Tangerang)'
    | 'Karawaci (Tangerang)'
    | 'Jatiuwung (Tangerang)'
    | 'Neglasari (Tangerang)'
    | 'Batuceper (Tangerang)'
    | 'Periuk (Tangerang)'
    | 'Cibeber (Cilegon)'
    | 'Ciwandan (Cilegon)'
    | 'Citangkil (Cilegon)'
    | 'Jombang (Cilegon)'
    | 'Cipocok Jaya (Serang)'
    | 'Curug (Serang Kota)'
    | 'Kasemen (Serang)'
    | 'Walantaka (Serang)'
    | 'Bandung Wetan (Bandung)'
    | 'Coblong (Bandung)'
    | 'Cidadap (Bandung)'
    | 'Sukajadi (Bandung)'
    | 'Sukasari (Bandung)'
    | 'Andir (Bandung)'
    | 'Astanaanyar (Bandung)'
    | 'Batununggal (Bandung)'
    | 'Kiaracondong (Bandung)'
    | 'Antapani (Bandung)'
    | 'Arcamanik (Bandung)'
    | 'Rancasari (Bandung)'
    | 'Gedebage (Bandung)'
    | 'Bekasi Barat'
    | 'Bekasi Timur'
    | 'Bekasi Utara'
    | 'Bekasi Selatan'
    | 'Medansatria (Bekasi)'
    | 'Rawalumbu (Bekasi)'
    | 'Pondokgede (Bekasi)'
    | 'Beji (Depok)'
    | 'Cimanggis (Depok)'
    | 'Pancoran Mas (Depok)'
    | 'Sukmajaya (Depok)'
    | 'Sawangan (Depok)'
    | 'Limo (Depok)'
    | 'Bogor Utara'
    | 'Bogor Selatan'
    | 'Bogor Barat'
    | 'Bogor Timur'
    | 'Bogor Tengah'
    | 'Tanah Sareal (Bogor)'
    | 'Cimahi Utara'
    | 'Cimahi Tengah'
    | 'Cimahi Selatan'
    | 'Harjamukti (Cirebon)'
    | 'Kejaksan (Cirebon)'
    | 'Kesambi (Cirebon)'
    | 'Lemahwungkuk (Cirebon)'
    | 'Cikole (Sukabumi)'
    | 'Citamiang (Sukabumi)'
    | 'Lembursitu (Sukabumi)'
    | 'Cihideung (Tasikmalaya)'
    | 'Tawang (Tasikmalaya)'
    | 'Kawalu (Tasikmalaya)'
    | 'Semarang Barat'
    | 'Semarang Timur'
    | 'Semarang Utara'
    | 'Semarang Selatan'
    | 'Tembalang (Semarang)'
    | 'Candisari (Semarang)'
    | 'Gajahmungkur (Semarang)'
    | 'Pedurungan (Semarang)'
    | 'Banjarsari (Solo)'
    | 'Jebres (Solo)'
    | 'Laweyan (Solo)'
    | 'Pasar Kliwon (Solo)'
    | 'Serengan (Solo)'
    | 'Magelang Utara'
    | 'Magelang Tengah'
    | 'Magelang Selatan'
    | 'Tegal Barat'
    | 'Tegal Timur'
    | 'Tegal Selatan'
    | 'Pekalongan Barat'
    | 'Pekalongan Timur'
    | 'Pekalongan Selatan'
    | 'Pekalongan Utara'
    | 'Sidorejo (Salatiga)'
    | 'Argomulyo (Salatiga)'
    | 'Kraton (Yogyakarta)'
    | 'Gondokusuman (Yogyakarta)'
    | 'Jetis (Yogyakarta)'
    | 'Umbulharjo (Yogyakarta)'
    | 'Kotagede (Yogyakarta)'
    | 'Danurejan (Yogyakarta)'
    | 'Surabaya Pusat'
    | 'Surabaya Barat'
    | 'Surabaya Timur'
    | 'Surabaya Utara'
    | 'Surabaya Selatan'
    | 'Tegalsari (Surabaya)'
    | 'Genteng (Surabaya)'
    | 'Wonokromo (Surabaya)'
    | 'Rungkut (Surabaya)'
    | 'Sukolilo (Surabaya)'
    | 'Klojen (Malang)'
    | 'Blimbing (Malang)'
    | 'Lowokwaru (Malang)'
    | 'Sukun (Malang)'
    | 'Kedungkandang (Malang)'
    | 'Batu (Kota Batu)'
    | 'Bumiaji (Batu)'
    | 'Junrejo (Batu)'
    | 'Mojoroto (Kediri)'
    | 'Kota (Kediri)'
    | 'Pesantren (Kediri)'
    | 'Kartoharjo (Madiun)'
    | 'Manguharjo (Madiun)'
    | 'Taman (Madiun)'
    | 'Kanigaran (Probolinggo)'
    | 'Wonoasih (Probolinggo)'
    | 'Mayangan (Probolinggo)'
    | 'Gadingrejo (Pasuruan)'
    | 'Purworejo (Pasuruan)'
    | 'Bugulkidul (Pasuruan)'
    | 'Magersari (Mojokerto)'
    | 'Prajurit Kulon (Mojokerto)'
    | 'Gresik (Kota)'
    | 'Manyar (Gresik)'
    | 'Denpasar Utara'
    | 'Denpasar Timur'
    | 'Denpasar Barat'
    | 'Denpasar Selatan'
    | 'Kuta (Badung)'
    | 'Kuta Selatan (Badung)'
    | 'Kuta Utara (Badung)'
    | 'Mengwi (Badung)'
    | 'Abiansemal (Badung)'
    | 'Jimbaran (Badung)'
    | 'Seminyak (Badung)'
    | 'Canggu (Badung)'
    | 'Nusa Dua (Badung)'
    | 'Uluwatu (Badung)'
    | 'Ubud (Gianyar)'
    | 'Gianyar (Kota)'
    | 'Sukawati (Gianyar)'
    | 'Tabanan (Kota)'
    | 'Kediri (Tabanan)'
    | 'Singaraja (Buleleng)'
    | 'Ampenan (Mataram)'
    | 'Cakranegara (Mataram)'
    | 'Mataram (Kota)'
    | 'Sekarbela (Mataram)'
    | 'Senggigi (Lombok Barat)'
    | 'Gerung (Lombok Barat)'
    | 'Kuta Mandalika (Lombok Tengah)'
    | 'Oebobo (Kupang)'
    | 'Maulafa (Kupang)'
    | 'Kelapa Lima (Kupang)'
    | 'Alak (Kupang)'
    | 'Kota Lama (Kupang)'
    | 'Medan Timur'
    | 'Medan Barat'
    | 'Medan Utara'
    | 'Medan Selatan'
    | 'Medan Kota'
    | 'Medan Johor'
    | 'Medan Sunggal'
    | 'Medan Denai'
    | 'Medan Tuntungan'
    | 'Medan Area'
    | 'Medan Polonia'
    | 'Binjai Kota'
    | 'Binjai Utara'
    | 'Binjai Selatan'
    | 'Siantar Barat'
    | 'Siantar Timur'
    | 'Siantar Utara'
    | 'Siantar Marihat'
    | 'Padang Barat'
    | 'Padang Timur'
    | 'Padang Utara'
    | 'Koto Tangah (Padang)'
    | 'Kuranji (Padang)'
    | 'Guguak Panjang (Bukittinggi)'
    | 'Aur Birugo Tigo Baleh'
    | 'Payakumbuh Barat'
    | 'Payakumbuh Timur'
    | 'Marpoyan Damai (Pekanbaru)'
    | 'Tampan (Pekanbaru)'
    | 'Rumbai (Pekanbaru)'
    | 'Payung Sekaki (Pekanbaru)'
    | 'Sukajadi (Pekanbaru)'
    | 'Batam Kota'
    | 'Lubuk Baja (Batam)'
    | 'Sekupang (Batam)'
    | 'Nongsa (Batam)'
    | 'Bukit Bestari (Tanjungpinang)'
    | 'Tanjungpinang Kota'
    | 'Ilir Timur I (Palembang)'
    | 'Ilir Timur II (Palembang)'
    | 'Ilir Barat I (Palembang)'
    | 'Ilir Barat II (Palembang)'
    | 'Seberang Ulu I (Palembang)'
    | 'Seberang Ulu II (Palembang)'
    | 'Sukarami (Palembang)'
    | 'Lubuklinggau Barat I'
    | 'Lubuklinggau Timur I'
    | 'Prabumulih Barat'
    | 'Prabumulih Timur'
    | 'Taman Sari (Pangkalpinang)'
    | 'Bukit Intan (Pangkalpinang)'
    | 'Pangkal Balam'
    | 'Tanjung Karang Pusat'
    | 'Tanjung Karang Timur'
    | 'Tanjung Karang Barat'
    | 'Kedaton (Bandar Lampung)'
    | 'Metro Pusat'
    | 'Metro Timur'
    | 'Pontianak Kota'
    | 'Pontianak Selatan'
    | 'Pontianak Utara'
    | 'Pontianak Timur'
    | 'Pontianak Barat'
    | 'Pontianak Tenggara'
    | 'Jekan Raya (Palangka Raya)'
    | 'Pahandut (Palangka Raya)'
    | 'Sebangau (Palangka Raya)'
    | 'Bukit Batu (Palangka Raya)'
    | 'Banjarmasin Timur'
    | 'Banjarmasin Barat'
    | 'Banjarmasin Tengah'
    | 'Banjarmasin Utara'
    | 'Banjarmasin Selatan'
    | 'Banjarbaru Utara'
    | 'Banjarbaru Selatan'
    | 'Balikpapan Kota'
    | 'Balikpapan Tengah'
    | 'Balikpapan Selatan'
    | 'Balikpapan Utara'
    | 'Balikpapan Barat'
    | 'Samarinda Kota'
    | 'Samarinda Ulu'
    | 'Samarinda Ilir'
    | 'Sungai Kunjang (Samarinda)'
    | 'Bontang Utara'
    | 'Bontang Selatan'
    | 'Bontang Barat'
    | 'Sepaku (Penajam Paser Utara)'
    | 'Tarakan Barat'
    | 'Tarakan Timur'
    | 'Tarakan Utara'
    | 'Tarakan Tengah'
    | 'Wenang (Manado)'
    | 'Sario (Manado)'
    | 'Malalayang (Manado)'
    | 'Tikala (Manado)'
    | 'Mapanget (Manado)'
    | 'Bunaken (Manado)'
    | 'Bitung Tengah'
    | 'Maesa (Bitung)'
    | 'Tomohon Utara'
    | 'Tomohon Selatan'
    | 'Kota Barat (Gorontalo)'
    | 'Dumbo Raya (Gorontalo)'
    | 'Hulonthalangi (Gorontalo)'
    | 'Palu Barat'
    | 'Palu Timur'
    | 'Palu Utara'
    | 'Palu Selatan'
    | 'Tatanga (Palu)'
    | 'Mamuju (Kota)'
    | 'Simboro (Mamuju)'
    | 'Ujung Pandang (Makassar)'
    | 'Panakkukang (Makassar)'
    | 'Biringkanaya (Makassar)'
    | 'Tamalate (Makassar)'
    | 'Manggala (Makassar)'
    | 'Rappocini (Makassar)'
    | 'Ujung Tanah (Makassar)'
    | 'Ujung (Parepare)'
    | 'Soreang (Parepare)'
    | 'Wara (Palopo)'
    | 'Telluwanua (Palopo)'
    | 'Baruga (Kendari)'
    | 'Kendari (Kota)'
    | 'Mandonga (Kendari)'
    | 'Murhum (Baubau)'
    | 'Kokalukuna (Baubau)'
    | 'Sirimau (Ambon)'
    | 'Nusaniwe (Ambon)'
    | 'Baguala (Ambon)'
    | 'Ternate Utara'
    | 'Ternate Selatan'
    | 'Ternate Tengah'
    | 'Tidore (Kota)'
    | 'Oba (Tidore Kep.)'
    | 'Manokwari Barat'
    | 'Manokwari Timur'
    | 'Sorong Barat'
    | 'Sorong Timur'
    | 'Sorong Utara'
    | 'Sorong Manoi'
    | 'Aimas (Sorong Kab.)'
    | 'Klabot (Sorong Kab.)'
    | 'Abepura (Jayapura)'
    | 'Heram (Jayapura)'
    | 'Jayapura Utara'
    | 'Jayapura Selatan'
    | 'Wamena (Jayawijaya)'
    | 'Asolokobal (Jayawijaya)'
    | 'Nabire (Kota)'
    | 'Mimika Baru (Timika)'
    | 'Tembagapura (Mimika)'
    | 'Merauke (Kota)'
    | 'Muting (Merauke)'
    | 'Baiturrahman (Banda Aceh)'
    | 'Meuraxa (Banda Aceh)'
    | 'Kuta Alam (Banda Aceh)'
    | 'Banda Sakti (Lhokseumawe)'
    | 'Muara Dua (Lhokseumawe)'
    | 'Gading Cempaka (Bengkulu)'
    | 'Ratu Agung (Bengkulu)'
    | 'Jambi Timur'
    | 'Jambi Selatan'
    | 'Kota Baru (Jambi)'
  )[];
  show_at_landing: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'blogs';
        value: string | Blog;
      } | null)
    | ({
        relationTo: 'partners';
        value: string | Partner;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: string | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  first_name?: T;
  last_name?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  main_description?: T;
  additional_description?: T;
  product_image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs_select".
 */
export interface BlogsSelect<T extends boolean = true> {
  author?: T;
  title?: T;
  overview?: T;
  content?: T;
  tags?: T;
  blog_image?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  partner_image?: T;
  location?: T;
  show_at_landing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}