name: Keep Alive

on:
  schedule:
    - cron: "0 0 * * 0,3" # Runs every Sunday and Wednesday
  workflow_dispatch:

jobs:
  send-http-request:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ github.ref == 'refs/head/main' && secrets.SUPABASE_PROD_URL || secrets.SUPABASE_DEV_URL }}
      PAYLOAD_FRONTEND_SHARED_SECRET: ${{ github.ref == 'refs/head/main' && secrets.PAYLOAD_FRONTEND_PROD_SHARED_SECRET || secrets.PAYLOAD_FRONTEND_DEV_SHARED_SECRET }}

    steps:
      - name: Send HTTP Request
        run: |
          curl -H "Authorization: Bearer ${{ env.PAYLOAD_FRONTEND_SHARED_SECRET }}" \
            "${{ env.SUPABASE_URL }}/keep-alive"
